### ISSUE TITLE
Add XML Comments for Intellisense

### ISSUE THREAD

**Issue by flcdrg** [approvals/ApprovalTests.Net#168] opened 2016-08-23 04:49 UTC
It would be helpful for public classes and interfaces to have useful XML comments so that end-users of the library get more details about what various methods and parameters are used for.

**Comment by isidore** [comment] 2016-08-23 07:35
The issue is it's very hard for me to write these as I can't tell the
difference between what is useful and what is obvious. Would you be willing
to do a skype call to experiment with some possible comments?

Llewellyn Falco
www.approvaltests.com

**Comment by flcdrg** [comment] 2016-08-23 10:27
Absolutely! I'm in a +930 timezone, so happy to find a mutually convenient time.

**Comment by isidore** [comment] 2016-08-23 11:08
I'm UTC+02:00 but pretty open this week. pick a time and send me a calendar
request and skype id.

my email is isidore at setgame com

Llewellyn Falco
www.approvaltests.com

**Comment by flcdrg** [comment] 2016-10-12 01:04
Here's some classes that I don't understand just from their name:

- ReportWithoutFrontLoading
-

**Comment by flcdrg** [comment] 2016-10-12 23:52
I think it would help to define what 'frontloaded' means. Is it the overriding/top-level reporter, or is it just for 'interactive' sessions (not for ci builds), or something else..

**Comment by flcdrg** [comment] 2019-02-14 01:09
I'm back thinking about this again. I'm wanting to use Approval tests on a new project, but discovered that I am going to have to call Approvals.Verify() directly (rather than use on of the more specific Verify* methods.. (because my 'approved' file exists in an existing directory and has a name that doesn't correspond to the default one ApprovalTests is expecting).

There's currently 9 overloads for Approvals.Verify() - some of these I can make sense, but some of them less so without having to drill into the source code and figure out what those things actually do..

eg. Verify(IApprovalWriter writer, IApprovalNamer namer, IApprovalFailureReporter reporter)..

What does a writer do? What does a namer do? What does a reporter do (well actually I think I can guess that last one!)

Having some documentation (eg. XML comment-style) on some of these methods and interfaces would b super helpful for me to narrow down to knowing which method is the correct one, and what all the requirements are for calling that.

**Comment by SimonCropp** [comment] 2020-05-16 00:31
closing this one. docs is never done. no one change will ever mean this can be closed. if anyone wants to contribute docs happy to consider and PRs

**Closed by SimonCropp** 2020-05-16 00:31 UTC
