### ISSUE TITLE
Weird ApprovalTests issue when running in TeamCity

### ISSUE THREAD

**Issue by kharabasz** [approvals/ApprovalTests.Net#66] opened 2014-02-24 10:13 UTC
Hello,

We have integrated ApprovalTests into our CI environment - unfortunately we are running into a weird issue around build agents.

When ApprovalTests run on the same build agent as they were built, there is no problem. Tests run, everyone is happy.

When ApprovalTests are run on a different build agent, we see the following error:

```
[_____.ApprovalTests] Test method _____.ApprovalTests.SomeApprovalTest threw exception: 
ApprovalTests.Core.Exceptions.ApprovalMissingException: Failed Approval: Approval File "c:\TeamCity\BuildAgent10\work\cf9524f6b7a5308c\_____.ApprovalTests\ApprovalTests\SomeApprovalTest.approved.txt" Not Found.
[10:50:24]
[_____.ApprovalTests.SomeApprovalTest]     at ApprovalTests.Approvers.FileApprover.Fail()
   at ApprovalTests.Core.Approvals.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter)
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer, IApprovalNamer namer, IApprovalFailureReporter reporter)
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer)
   at ApprovalTests.Approvals.Verify(String text)
   at ApprovalTests.Approvals.VerifyAll[T](IEnumerable`1 enumerable, String label)
   at _____.ApprovalTests.SomeApprovalTest () in c:\TeamCity\BuildAgent10\work\cf9524f6b7a5308c\_____.ApprovalTests\ApprovalsFixture.cs:line 34
```

It looks like the test runner is looking for the *.approved.txt files based on their first location? 

We have tried to resolve this using DeploymentItems, and by using the [assembly: FrontLoadedReporter(typeof(TeamCityReporter))] annotation - with no success.

I have been able to recreate this issue locally, by running ApprovalTests using MSTest from the cmd line from a different folder than they were built to.

**Comment by jnsn** [comment] 2015-06-24 06:00
I am running into the same issue, using Bamboo. I have a plan consisting of multiple stages and each stage has it's own working directory. To share build items between two stages, the first stage has to publish them. So basically, what happens is the following:

* Stage 1
  * Check out sources
  * Build project
  * Zip entire MyProjects.Test folder (including .csproj, sources and bin/Release)
  * Upload zip
* Stage 2
  * Download zip
  * Run tests

I have not tried the attributes trick, but I'd like to give some input.

Our approved files are checked in, but they are not part of the .cproj file and therefore not copied to the output folder. But by default they show up in the same folder as where the test class was. I sometimes use the NamerFactory.AdditionalInfo to generate a more useful name.

Since I'm also using SpecFlow, I need to zip the entire MyProject.Test folder because SpecFlow analyses the .csproj file for .feature files. So the .csproj file is a mandatory argument.

Wouldn't it be possible for ApprovalTests to do the same? I don't know about the other test frameworks, but NUnit is capable of running the tests when I pass the .csproj file without the need to recompile everything. I've noticed that in https://github.com/approvals/ApprovalTests.Net/pull/124 several assumptions are made based on the namespace and path, but if you'd were to analyze the .csproj file based upon the current class you are processing, wouldn't it be possible to match the relative path?

**Comment by julian-maughan** [comment] 2015-06-25 15:34
@jnsn Good to hear from you. Your understanding of the way SpecFlow works doesn't make sense to me. In particular, to run SpecFlow, it shouldn't be necessary to copy the whole MyProjects.Test folder to Stage 2 - only the build outputs.

SpecFlow does not require a .feature file at run time; only design time. During development, .feature files produce a code-behind class containing NUnit tests (or whatever testing framework you are using), which can be run just as if they were normal NUnit tests that you had written yourself...they are compiled into the assembly.

I don't know if this helps, but you can run nunit-console.exe with an assembly parameter...not just .csproj file

IMO ApprovalTests should also be able to be run without the source-code folder, provided the approval files are available in a sensible location that can be discovered. This is what #71 and #124 attempt to achieve.

I'm using NUnit, SpecFlow and Bamboo (building on one machine and running tests on another) and it is all working as intended. Its a slightly different implementation from the one I provided in #124, but its the same technique of locating the approval files relative to the test assembly.

If you didn't want to add the approval files to your project file (so they can be copied to the build output folder at compile time), you could have a separate Bamboo task to copy them?

**Comment by jnsn** [comment] 2015-06-25 15:51
Yeah, I should have clarified that.

SpecFlow requires the .csproj file to generate an HTML report, not to run the test itself.

**Comment by isidore** [comment] 2015-06-25 16:59
Hey everyone. Any chance one or both of you could Skype tomorrow and we could fix this completely and push it?

Llewellyn Falco

**Comment by CarlVerret** [comment] 2017-02-28 01:57
Hi,
I've been facing the same issue with a TFS build agent when trying to run (via Functional tests in TFS) the test runner can't find the *.approved files.  Any ideas how to set the path to find them ?

Thanks

**Comment by danpowell88** [comment] 2017-07-05 05:26
Did anything ever happen with this?

**Comment by davidalpert** [comment] 2019-04-19 20:52
@danpowell88 @CarlVerret check out #219 - that fix worked for me to fix missing MSTest approval files in a Jenkins CIBuild

**Comment by SimonCropp** [comment] 2019-11-14 21:02
given @davidalpert comment we can close this one.

**Closed by SimonCropp** 2019-11-14 21:02 UTC
